name: actions
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.13.1
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm set //registry.npmjs.org/:_authToken={{secrets.NPM_TOKEN}}
      - run: npm publish --access public

